# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo_miccall.png"
    high_res_favicon: "/img/logo_miccall.png"
    apple_touch_icon: "/img/logo_miccall.png"
    keywords: miccall

Intro:
    name: SOR
    slogan: "Sistemas operativos de red."
    HeadButton: SOR

Nav:
    Home_name: Sistemas operativos de red.
    is_use_categories : true
    # categories_name: chidi
    is_use_archives : false
    archives_name: Archivos
    icon:
        github:
            use: true
            link: https://github.com/donluigimx
        Twitter:
            use: false
            link:
        Facebook:
            use: false
            link:
        Instagram:
            use: false
            link:
    pages:


MainFirst:
    name: SSPSOR
    description: Seminario de Solución de Problemas de Sistemas Operativos de Red
    pic_url: /images/logo_udg-gris.png
    goto_ulr: ""

Gallery :
    title: Mr.metro
    description: Just another fine responsive

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染
# default dark funky okaidia twilight coy solarized  可选项
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: disqus_click
    shortname: cuceisor2017
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Sistemas operativos de red


# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
